### ISSUE TITLE
Compatibility with Beta 8

### ISSUE THREAD

**Issue by PeopleInside** [ReFlar/user-management#26]
Will be this upgraded for work with Beta 8?
I need to have a list of registered users.

Thank you for this extension.

**Comment by Ralkage** [comment]
Hi, @PeopleInside 

We are planning a MAJOR overhaul of this extension before we release a compatibility fix for Beta 8.1.

These are changes that will be proposed:

1. Split the Strikes system into it's own extension since it is out of the scope of this extension itself (we were younger and learning about Flarum extension development at this point in time)
2. Removal of the current user registration tweaks in this extension in favor of creating a separate extension as well.
3. Adding user creation through the Admin CP like all other forum software has as part of their core functionality.

In the meantime, you can look forward to [Flagrow's User List extension](https://discuss.flarum.org/d/6009-flagrow-users-list-review-and-mass-mail-users-of-your-forum) that will include a forum-end and admin-end UI in the near future as well as an update to make it compatible with Beta 8.1 :)

**Comment by Ralkage** [comment]
@PeopleInside please see https://discuss.flarum.org/d/5444-user-management-by-reflar/229 for the full update :D

With that being said, we will be closing this issue.

**Result:** User Management will be deprecated in favor of an updated extension with more specific features pertaining to the scope of the project.
